version: "3"
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: customerdatabase
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  mysqllesson:
    image: mysqllesson:latest
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
